name: Guilds
version: '1.0.0'
main: org.aincraft.GuildsPlugin
api-version: 1.21.7
description: A comprehensive guild system for Minecraft servers
author: Ainecraft
website: https://github.com/aincraft

permissions:
  guilds.use:
    description: Allow use of guild commands
    default: false
  guilds.create:
    description: Allow creating guilds
    default: false
  guilds.join:
    description: Allow joining guilds
    default: false
  guilds.leave:
    description: Allow leaving guilds
    default: false
  guilds.delete:
    description: Allow deleting guilds
    default: false
  guilds.disband:
    description: Allow disbanding guilds
    default: false
  guilds.info:
    description: Allow viewing guild info
    default: false
  guilds.list:
    description: Allow listing all guilds
    default: false
  guilds.claim:
    description: Allow claiming chunks
    default: false
  guilds.unclaim:
    description: Allow unclaiming chunks
    default: false
  guilds.kick:
    description: Allow kicking guild members
    default: false
  guilds.invite:
    description: Allow inviting players to guild
    default: false
  guilds.role:
    description: Allow managing guild roles
    default: false
  guilds.map:
    description: Allow viewing guild map
    default: false
  guilds.spawn:
    description: Allow teleporting to guild spawn
    default: false
  guilds.setspawn:
    description: Allow setting guild spawn
    default: false
  guilds.ally:
    description: Allow managing alliances
    default: false
  guilds.enemy:
    description: Allow managing enemies
    default: false
  guilds.neutral:
    description: Allow declaring neutral status
    default: false
  guilds.description:
    description: Allow changing guild description
    default: false
  guilds.name:
    description: Allow changing guild name
    default: false
  guilds.color:
    description: Allow changing guild color
    default: false
  guilds.chat:
    description: Allow using guild and ally chat
    default: false
  guilds.upgrade:
    description: Allow leveling up the guild
    default: false
  guilds.owner:
    description: Allow viewing guild owner
    default: false
  guilds.member:
    description: Allow viewing member information
    default: false
  guilds.toggle:
    description: Allow toggling guild settings
    default: false
  guilds.transfer:
    description: Allow transferring guild ownership
    default: false
  guilds.outpost:
    description: Allow managing guild outposts
    default: false
  guilds.skills:
    description: Allow managing guild skills
    default: false
  guilds.project:
    description: Allow managing guild projects
    default: false
  guilds.region:
    description: Allow managing guild regions
    default: false
  guilds.admin.bypass:
    description: Bypass all guild claim protections
    default: op
  guilds.admin.typelimits:
    description: Allow managing region type volume limits
    default: op
  guilds.admin:
    description: All guild permissions
    children:
      - guilds.use
      - guilds.create
      - guilds.join
      - guilds.leave
      - guilds.delete
      - guilds.disband
      - guilds.kick
      - guilds.invite
      - guilds.info
      - guilds.list
      - guilds.claim
      - guilds.unclaim
      - guilds.map
      - guilds.role
      - guilds.spawn
      - guilds.setspawn
      - guilds.ally
      - guilds.enemy
      - guilds.neutral
      - guilds.description
      - guilds.name
      - guilds.color
      - guilds.chat
      - guilds.upgrade
      - guilds.owner
      - guilds.member
      - guilds.toggle
      - guilds.transfer
      - guilds.outpost
      - guilds.skills
      - guilds.project
      - guilds.region
      - guilds.admin.bypass
      - guilds.admin.typelimits
    default: op