package org.aincraft.guilds.territory.building;

public enum AnchorStatus {
    ACTIVE,
    WORLD_UNAVAILABLE,
    WRONG_MATERIAL,
    OUTSIDE_TERRITORY,
    MISSING_GEOMETRY,
    INVALID_GEOMETRY,
    SPAWN_MISMATCH,
    GOVERNANCE_MISSING,
    CAPABILITY_MISSING,
    QUOTA_EXCEEDED,
    CARDINALITY_EXCEEDED,
    BOAT_ENTRY_UNAVAILABLE,
    AIRSHIP_PLATFORM_UNAVAILABLE,
    AIRSHIP_CLEARANCE_BLOCKED
}
