plugins {
    id("xyz.jpenilla.run-paper") version "3.0.2"
}

description = "Guilds local test server — run-paper harness that boots Paper with the guilds shadow jar as the test plugin"
val placeholderApiVersion = rootProject.property("placeholderApiVersion").toString()

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.2.build.111-stable")
}

tasks.processResources {
    val props = mapOf(
            "version" to version,
            "description" to (project.description ?: ""),
    )
    inputs.properties(props)
    filesMatching("plugin.yml") {
        expand(props)
    }
}

// Local test server: ./gradlew :guilds-test:runServer
// Boots Paper 26.2 with the guilds shadow jar plus the squaremap
// 1.3.15 Paper jar (pinned GitHub release asset) loaded as plugins. squaremap
// serves its live web map on http://localhost:18080 when using the local Rust backend.
// Mint economy plugin — resolved as a Maven dependency from the aincraft-org/mint
// GitHub Packages repository (configured in settings.gradle.kts). The cached
// mint-paper fat jar bundles mint-core and mint-postgres, so no transitive
// resolution is needed. The jar is loaded as a Paper plugin alongside Guilds.
val mintPlugin = configurations.create("mintPlugin")
dependencies {
    add("mintPlugin", "dev.mintychochip.mint:mint-paper:${property("mintPaperVersion")}") {
        isTransitive = false
    }
}
val mintPaperJarFile: java.io.File = mintPlugin.files.first { it.name.contains("mint-paper") }

// Writes the Mint plugin config and patches the Guilds config for MINT economy
// mode before runServer boots. On a clean run directory the Guilds config is
// created from the guilds-paper template with local dev database settings; on
// an existing run directory only the economy section is patched so manual
// config changes are preserved.
val writeMintConfigs = tasks.register("writeMintConfigs") {
    group = "run"
    description = "Write Mint plugin config and patch Guilds config for MINT economy mode"
    doLast {
        val runDir = layout.projectDirectory.dir("run").asFile

        // --- Mint plugin config ---
        val mintDir = runDir.resolve("plugins/Mint")
        mintDir.mkdirs()
        mintDir.resolve("config.yml").writeText(
            """
            # Mint durable-economy runtime configuration.
            # Generated by :guilds-test:writeMintConfigs — do not edit; re-run the task.
            runtime:
              admission-capacity: 64
            currency:
              id: mint:coins
              display-name: Coins
              symbol: ¢
              scale: 2
              active: true
              policies: []
            database:
              enabled: true
              jdbc-url: jdbc:mysql://localhost:3306/mint
              username: mint
              password: mint
              pool-size: 10
              connection-timeout-ms: 5000
              soft-mode: false
              check-durable-on-accept: false
              microbatch-max: 64
              queue-capacity: 1024
              flush-interval-ms: 50
              lanes: 4
            integrations:
              policy-providers: []
              vault-plugin: MintVaultBridge
              profiles:
              - plugin: Guilds
                profile-id: profile:guilds
                revision: 1
                client-id: plugin:guilds
                actor-id: plugin:guilds
                actions: [ACCOUNT_CREATE, ACCOUNT_READ, BALANCE_READ, TRANSFER, RECEIPT_READ]
                account-scopes:
                - kind: NAMESPACE
                  namespace: player
                  access: [CREATE, READ, DEBIT, CREDIT]
                - kind: NAMESPACE
                  namespace: guild
                  access: [CREATE, READ, DEBIT, CREDIT]
                currency-scopes:
                - kind: EXACT
                  currency: mint:coins
                  access: [READ, USE]
                providers: []
                hold-control: NONE
                quote-control: NONE
                schedule-control: NONE
                max-in-flight: 16
            exchange:
              pairs: []
            """.trimIndent() + "\n",
        )

        // --- Guilds config: patch economy.mode to MINT ---
        val guildsConfig = runDir.resolve("plugins/Guilds/config.yml")
        if (guildsConfig.isFile) {
            // Existing config: patch only the economy section.
            val text = guildsConfig.readText()
            guildsConfig.writeText(
                text
                    .replace("mode: SIMULATION", "mode: MINT")
                    .replace("currency: coins", "currency: mint:coins"),
            )
        } else {
            // Fresh checkout: create from guilds-paper template with local dev settings.
            val template = rootProject.file("guilds-paper/src/main/resources/config.yml")
            val text = template.readText()
            guildsConfig.parentFile.mkdirs()
            guildsConfig.writeText(
                text
                    .replace("name: azoth_territory", "name: guilds")
                    .replace("user: azoth", "user: guilds")
                    .replace("password: \"\"", "password: \"guilds\"")
                    .replace("enabled: false", "enabled: true")
                    .replace("api-token: \"\"", "api-token: \"dev-token\"")
                    .replace("mode: SIMULATION", "mode: MINT")
                    .replace("currency: coins", "currency: mint:coins"),
            )
        }
    }
}

// The guilds shadow jar is the plugin under test; the guilds-test jar is the
// test plugin loaded alongside it. The shadow jar is wired as a task provider
// so every runServer boot builds and loads the current plugin rather than a
// stale jar left in build/libs.
val guildsPaperProject = project(":guilds-paper")
val guildsShadowJar = guildsPaperProject.tasks.named<Jar>("shadowJar")
val testPluginJar: java.io.File =
    layout.projectDirectory.dir("build/libs")
        .file("guilds-test-${project.version}.jar")
        .asFile

// squaremap is loaded as a plugin. Default to the upstream Java squaremap release
// (no Rust sidecar); set -PsquaremapLocalRust=true to use the locally-built
// Rust-backed jar (run/squaremapmap-paper-rust-local.jar) with its sidecar.
val useLocalRustSquaremap = providers.gradleProperty("squaremapLocalRust")
    .map { it.equals("true", ignoreCase = true) }
    .orElse(false)
val squaremapJarFile: java.io.File =
    if (useLocalRustSquaremap.get()) {
        layout.projectDirectory.file("run/squaremap-paper-rust-local.jar").asFile
    } else {
        layout.projectDirectory.file("run/squaremap-paper-upstream.jar").asFile
    }

tasks.runServer {
    minecraftVersion("26.2")
    runDirectory.set(layout.projectDirectory.dir("run"))
    pluginJars(guildsShadowJar.flatMap { it.archiveFile }, testPluginJar, squaremapJarFile, mintPaperJarFile)
    dependsOn(guildsShadowJar, tasks.jar, writeMintConfigs)
    downloadPlugins {
        // MapGUI is a hard dependency of the Guilds plugin (plugin.yml `depend`).
        // run-paper downloads the release jar into run/plugins so the server boots.
        github("FloG99", "MapGUI", "v2.0.0", "MapGUI-2.0.0.jar")
        github(
            "PlaceholderAPI",
            "PlaceholderAPI",
            placeholderApiVersion,
            "PlaceholderAPI-$placeholderApiVersion.jar",
        )
    }
}

// The local Rust-backed squaremap is mandatory: pass backend binary and
// output root as JVM system properties. Current squaremap serves the SPA from
// SQUAREMAP_WEB_ROOT (plugin web dir) and tiles from SQUAREMAP_OUTPUT_ROOT
// (rust-output). syncSquaremapWebToRustOutput still copies the SPA into
// rust-output so a sidecar without web_root keeps working.
val sidecarPath = providers.gradleProperty("squaremapBackendBinary")
    .orElse(layout.projectDirectory.file("run/squaremap-server").asFile.absolutePath)
val backendOutputRoot = providers.gradleProperty("squaremapBackendOutputRoot")
    .orElse(layout.projectDirectory.dir("run/rust-output").asFile.absolutePath)
val backendWebRoot = providers.gradleProperty("squaremapBackendWebRoot")
    .orElse(layout.projectDirectory.dir("run/plugins/squaremap/web").asFile.absolutePath)
val localJar = squaremapJarFile

val ensureSquaremapWebAssets = tasks.register<Exec>("ensureSquaremapWebAssets") {
    group = "run"
    description = "Extract bundled squaremap web UI into run/plugins/squaremap/web on first run"
    val webDir = layout.projectDirectory.dir("run/plugins/squaremap/web")
    val pluginDir = layout.projectDirectory.dir("run/plugins/squaremap")
    doFirst {
        pluginDir.asFile.mkdirs()
    }
    commandLine(
        "unzip",
        "-qo",
        localJar.absolutePath,
        "web/*",
        "-d",
        pluginDir.asFile.absolutePath,
    )
    onlyIf { localJar.isFile && !webDir.asFile.resolve("index.html").isFile }
}

val syncSquaremapWeb = tasks.register<Exec>("syncSquaremapWebToRustOutput") {
    group = "run"
    description = "Copy squaremap web UI assets into rust-output (tiles/ excluded; sidecar renders PNGs live)"
    dependsOn(ensureSquaremapWebAssets)
    val webDir = layout.projectDirectory.dir("run/plugins/squaremap/web")
    val outputRoot = layout.projectDirectory.dir("run/rust-output")
    doFirst {
        outputRoot.asFile.mkdirs()
    }
    commandLine(
        "rsync", "-a",
        "--exclude", "tiles",
        webDir.asFile.absolutePath + "/",
        outputRoot.asFile.absolutePath + "/",
    )
    onlyIf { webDir.asFile.resolve("index.html").isFile }
}

// Optional stale-tile bootstrap: copies bundled web/tiles into rust-output and can
// mask a broken renderer. Off by default; enable only for temporary UI smoke tests:
//   ./gradlew :guilds-test:runServer -PsquaremapBootstrapStaleTiles=true
val bootstrapSquaremapTiles = providers.gradleProperty("squaremapBootstrapStaleTiles")
    .map { it.equals("true", ignoreCase = true) }
    .orElse(false)
val bootstrapSquaremapTilesTask = tasks.register<Exec>("bootstrapSquaremapTilesIfEmpty") {
    group = "run"
    description = "TEMPORARY: seed rust-output/tiles from bundled web tiles (masks live rendering)"
    dependsOn(syncSquaremapWeb)
    val webTiles = layout.projectDirectory.dir("run/plugins/squaremap/web/tiles")
    val outputTiles = layout.projectDirectory.dir("run/rust-output/tiles")
    doFirst {
        outputTiles.asFile.mkdirs()
    }
    commandLine(
        "rsync", "-a",
        webTiles.asFile.absolutePath + "/",
        outputTiles.asFile.absolutePath + "/",
    )
    onlyIf {
        bootstrapSquaremapTiles.get() &&
            webTiles.asFile.isDirectory &&
            outputTiles.asFile.walkTopDown().none { it.isFile && it.extension == "png" }
    }
}

val syncSquaremapBackendManifest = tasks.register<Exec>("syncSquaremapBackendManifest") {
    group = "run"
    description = "Patch squaremap-backends.json in the local Rust jar to match run/squaremap-server"
    val patchScript = layout.projectDirectory.file("scripts/sync-squaremap-backend-manifest.py")
    inputs.file(localJar)
    inputs.file(sidecarPath)
    inputs.file(patchScript)
    outputs.file(localJar)
    onlyIf {
        localJar.isFile &&
            file(sidecarPath.get()).isFile &&
            patchScript.asFile.isFile
    }
    commandLine(
        "python3",
        patchScript,
        localJar,
        sidecarPath.get(),
    )
}

tasks.runServer {
    doFirst {
        require(guildsShadowJar.get().archiveFile.get().asFile.isFile) {
            "Guilds shadow jar missing: ${guildsShadowJar.get().archiveFile.get().asFile} — build it with ./gradlew :guilds-paper:shadowJar"
        }
        require(testPluginJar.isFile) {
            "Test plugin jar missing: $testPluginJar — build it with ./gradlew :guilds-test:jar"
        }
        require(squaremapJarFile.isFile) {
            "Local squaremap jar missing: $squaremapJarFile — build it with ./scripts/build-squaremap-local.sh"
        }
        require(mintPaperJarFile.isFile) {
            "Mint paper jar missing: $mintPaperJarFile — resolve with ./gradlew :guilds-test:dependencies"
        }
        if (useLocalRustSquaremap.get()) {
            require(file(sidecarPath.get()).isFile) {
                "Local squaremap backend missing: ${sidecarPath.get()} — build it with ./scripts/build-squaremap-local.sh"
            }
        }
    }
    if (useLocalRustSquaremap.get()) {
        systemProperty("squaremap.backendBinary", sidecarPath.get())
        systemProperty("squaremap.backendOutputRoot", backendOutputRoot.get())
        systemProperty("squaremap.backendWebRoot", backendWebRoot.get())
        dependsOn(syncSquaremapWeb, bootstrapSquaremapTilesTask, syncSquaremapBackendManifest)
    }
}
